"""add auth models

Revision ID: 3e30f6988dc3
Revises: 
Create Date: 2026-05-19 22:59:36.751272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e30f6988dc3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('iiko_customer_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_iiko_customer_id'), 'customers', ['iiko_customer_id'], unique=True)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    op.create_table('otp_challenges',
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('attempts_left', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resend_available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_challenges_expires_at'), 'otp_challenges', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_challenges_phone'), 'otp_challenges', ['phone'], unique=False)
    op.create_table('refresh_sessions',
    sa.Column('subject_type', sa.Enum('customer', 'staff', name='authsubjecttype'), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_sessions_device_id'), 'refresh_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_refresh_sessions_expires_at'), 'refresh_sessions', ['expires_at'], unique=False)
    op.create_index('ix_refresh_sessions_subject', 'refresh_sessions', ['subject_type', 'subject_id'], unique=False)
    op.create_index(op.f('ix_refresh_sessions_token_hash'), 'refresh_sessions', ['token_hash'], unique=True)
    op.create_table('staff_users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', name='staffrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_users_email'), 'staff_users', ['email'], unique=True)
    op.create_index(op.f('ix_staff_users_phone'), 'staff_users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_users_phone'), table_name='staff_users')
    op.drop_index(op.f('ix_staff_users_email'), table_name='staff_users')
    op.drop_table('staff_users')
    op.drop_index(op.f('ix_refresh_sessions_token_hash'), table_name='refresh_sessions')
    op.drop_index('ix_refresh_sessions_subject', table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_expires_at'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_device_id'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index(op.f('ix_otp_challenges_phone'), table_name='otp_challenges')
    op.drop_index(op.f('ix_otp_challenges_expires_at'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_iiko_customer_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
